### ISSUE TITLE
Extension incompatible with Quarkus 3.4.0

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-vault#165]
When building the Vault extension with 3.4.0.CR1, we get:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project quarkus-vault: Compilation failure
[ERROR] /home/gsmet/git/quarkus-vault/runtime/src/main/java/io/quarkus/vault/runtime/client/SharedVertxVaultClient.java:[17,32] cannot find symbol
[ERROR]   symbol:   class VertxRecorder
[ERROR]   location: package io.quarkus.vertx.runtime
```

The `VertxRecorder` is gone in 3.4.0.

TBH, I'm not completely sure where it's gone, maybe @geoand and @cescoffier know :).

**Comment by geoand** [comment]
`VertxEventBusConsumerRecorder`

**Comment by cescoffier** [comment]
Wait? Why do they need the recorder? I need to check why they do need this recorder.

**Comment by cescoffier** [comment]
I just checked. I'm a bit worried. It seems they retrieve the vertx instance from the event bus recorder. First it should be on the vertx core recorder and not the event bus one. Then, I don't see why it cannot be accessed using Arc. 

If we need a getter, we should consider adding a public API for that.

**Comment by kdubb** [comment]
[Here is the PR](#109) where we switched to using `VertxRecorder`.

>  It seems they retrieve the vertx instance from the event bus recorder

I have no idea where this is happening.

**Comment by vsevel** [comment]
where are we on this? is there something to do? if so, what should be done?

**Comment by cescoffier** [comment]
First we need to understand why the extension cannot use Arc API to retrieve the vertx instance.

**Comment by geoand** [comment]
If all that is needed is a Vert.x instance, it's easy to get. Let me see if I can open a PR in under 5 minutes :)

**Comment by vmargerin** [comment]
Hi @geoand,

VertxRecorder is still used in SharedVertxVaultClient constructor:
```java 
public SharedVertxVaultClient(VaultConfigHolder vaultConfigHolder, TlsConfig tlsConfig) {
        super(vaultConfigHolder.getVaultRuntimeConfig().url().orElseThrow(() -> new VaultException("no vault url provided")),
                vaultConfigHolder.getVaultRuntimeConfig().enterprise().namespace(),
                vaultConfigHolder.getVaultRuntimeConfig().readTimeout());
        Vertx vertx = Vertx.newInstance(VertxRecorder.getVertx());
        this.webClient.set(createHttpClient(vertx, vaultConfigHolder.getVaultRuntimeConfig(), tlsConfig));
    }
```

**Comment by geoand** [comment]
Good point, I have updated the PR
