### ISSUE TITLE
Add PEM_BUNDLE to pki DataFormat enum

### ISSUE THREAD

**Issue by aaronz-vipaso** [quarkiverse/quarkus-vault#192]
I would like to sign a certificate with the PKI engine and use [the `pem_bundle` format](https://developer.hashicorp.com/vault/api-docs/secret/pki#format-2). Currently, the DataFormat enum only contains `der` and `pem`. 

Is it only required to add another entry [in `io.quarkus.vault.pki.DataFormat`](https://github.com/quarkiverse/quarkus-vault/blob/main/runtime/src/main/java/io/quarkus/vault/pki/DataFormat.java) to solve this?

**Comment by kdubb** [comment]
@aaronz-vipaso That would be 1 thing that needs to happen. Additionally the `CertificateData` class would need to be updated to be able to handle that format and the API requests would need to be able to select that format (passed in from the model class `GenerateCertificateOptions`) and then be able to process the resultant data into a `CertificateData`.

**Comment by kdubb** [comment]
@aaronz-vipaso This is now doable with the new client introduced in 4.+
