### ISSUE TITLE
Userpass authentication method does not support custom mount path

### ISSUE THREAD

**Issue by kdubb** [quarkiverse/quarkus-vault#269]
### Discussed in https://github.com/quarkiverse/quarkus-vault/discussions/173

<div type='discussions-op-text'>

<sup>Originally posted by **davetrux** September 29, 2023</sup>
In our instance of Vault, the admin named the userpass authentication method something different than "userpass".

Using curl, I can login by changing the path from `v1/auth/userpass/login` to `/v1/auth/othername/login/` and it works.

I have not been able to find a configuration for our Quarkus app that works. The app cannot connect, it just gets 403 responses back from Vault, because it's trying to use `v1/auth/userpass/login`.

In our Quarkus app, what can I configure to have the same effect as the curl login? </div>

**Comment by zsmeier** [comment]
This should be the Problem i had, fixed with https://github.com/quarkiverse/quarkus-vault/pull/268
