### ISSUE TITLE
Use Maven to generate a Jandex index instead of indexing at every build

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-vault#6]
I think this should be avoided:
https://github.com/quarkiverse/quarkus-vault/blob/main/deployment/src/main/java/io/quarkus/vault/deployment/VaultProcessor.java#L61
and a Jandex index created by Maven via the Jandex Maven plugin for the quarkus-vault-model artifact instead.

/cc @vsevel

**Comment by vsevel** [comment]
good catch @gsmet :)
